[package]
name = "sats_por_real"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
nostr-sdk = "0.37.0"
reqwest = "0.12.8"
separator = "0.4.1"
serde = "1.0.213"
serde_json = "1.0.132"
thousands = "0.2.0"
tokio = "1.41.0"
tweety-rs = "0.1.4"
